apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        autoscaling.knative.dev/target-burst-capacity: "-1"
        autoscaling.knative.dev/window: "12s"
        autoscaling.knative.dev/min-scale: "3"
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/target: "10"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
                - node2
                - node3
      containers:
      - image: docker.io/bonavadeur/shuka:v1.0
        resources:
          limits:
            cpu: 500m
            memory: 640M
        env:
        - name: TARGET
          value: "Konnichiwa"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: hello
  name: hello
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    interval: 1s
    path: /metrics
    port: http-usermetric
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      serving.knative.dev/service: hello
---
