apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: alpha
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        autoscaling.knative.dev/target-burst-capacity: "-1"
        autoscaling.knative.dev/window: "12s"
        # DO NOT set the following two lines
        # autoscaling.knative.dev/min-scale: "3"
        # autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: docker.io/bonavadeur/shuka:v1.3
        resources:
          limits:
            cpu: 500m
            memory: 640M
        env:
        - name: TARGET
          value: "alpha"
